### ISSUE TITLE
Delete Port not Working in Admin

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [mesh0000/poolui#29]
Hey, I'm trying to get the delete port working in admin.. I started rewriting the app in Ionic/Angular 5.. for starters, the poolui version of the site's port delete feature is not working. Also, Angular 5's HttpClient only accepts two parameters and can not post data in the delete. It should be something like this:

```
this.httpClient.delete(AdminPortURL + '?' + portToDelete, headers);
```

Anyone know how I can get this working?

**Comment by Weiss1985** [comment]
```
2018-07-29 19:15 +00:00: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (/home/weiss/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/home/weiss/nodejs-pool/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/weiss/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/weiss/nodejs-pool/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/weiss/nodejs-pool/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/weiss/nodejs-pool/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
    --------------------
    at Pool.query (/home/weiss/nodejs-pool/node_modules/mysql/lib/Pool.js:199:23)
    at /home/weiss/nodejs-pool/node_modules/promise-mysql/lib/helper.js:16:24
    at Promise._execute (/home/weiss/nodejs-pool/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/weiss/nodejs-pool/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/home/weiss/nodejs-pool/node_modules/bluebird/js/release/promise.js:77:14)
    at Pool.promiseCallback (/home/weiss/nodejs-pool/node_modules/promise-mysql/lib/helper.js:6:10)
    at pool.query (/home/weiss/nodejs-pool/node_modules/promise-mysql/lib/pool.js:23:28)
    at /home/weiss/nodejs-pool/lib/api.js:681:18
    at Layer.handle [as handle_request] (/home/weiss/nodejs-pool/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/weiss/nodejs-pool/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/weiss/nodejs-pool/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/weiss/nodejs-pool/node_modules/express/lib/router/layer.js:95:5)
    at /home/weiss/nodejs-pool/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/weiss/nodejs-pool/node_modules/express/lib/router/index.js:330:12)
    at next (/home/weiss/nodejs-pool/node_modules/express/lib/router/index.js:271:10)
    at /home/weiss/nodejs-pool/lib/api.js:564:17

```
When you want to change port or delete. Jumps into the logs of the stub

And if you want to add it just does not do anything.
Similarly, if you remove the port through the database and then start api, the remote port appears back.

**Comment by Weiss1985** [comment]
help please!!
